# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
            #https://circleci.com/developer/images/image/cimg/node
            - image: 14.16.1-browsers

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/mongo:3.4.4

        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
                      - v1-dependencies

            - run: |
              node --version
              yarn install

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

            - run:
                  name: test
                  command: |
                      yarn lint
                      yarn test
                  # later?!
                  #yarn itest

            - run:
                  name: package
                  command: |
                      yarn vsce-package
